# Copyright cocotb contributors
# Copyright (c) 2025 Benycze
# Licensed under the Revised BSD License, see LICENSE for details.
# SPDX-License-Identifier: BSD-3-Clause

TOPLEVEL_LANG=verilog
PWD=$(shell pwd)
TOPLEVEL := top
VERILOG_SOURCES = $(PWD)/test_struct_bus.sv

MODULE = test_struct_bus
include $(shell cocotb-config --makefiles)/Makefile.sim